# Generated by Django 4.2 on 2024-07-23 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_settings_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "permissions": [
                    ("see_list_of_clients", "Просмотр списка пользователей сервиса"),
                    ("ban_clients", "Блокирование пользователей сервиса"),
                ],
                "verbose_name": "клиент",
                "verbose_name_plural": "клиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [("change_mailing_message", "Изменение сообщения")],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AlterModelOptions(
            name="settings",
            options={
                "permissions": [
                    ("see_any_mailing_settings", "Просмотр любых рассылок"),
                    ("switch_of_mailing_settings", "Отключение рассылки"),
                    ("change_mailing_settings", "Редактирование рассылки"),
                    ("manage_list_of_mailing_settings", "Управление списком рассылки"),
                ],
                "verbose_name": "Настройки рассылки",
                "verbose_name_plural": "Настройки рассылок",
            },
        ),
    ]
