# Generated by Django 4.2 on 2024-07-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_client_options_alter_message_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="is_banned",
            field=models.BooleanField(default=False, verbose_name="Блокирован"),
        ),
    ]
