# Generated by Django 4.2 on 2024-07-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_client_is_banned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="end_time",
            field=models.DateTimeField(
                blank=True,
                help_text="ДД.ММ.ГГГГ 00:00",
                null=True,
                verbose_name="Время завершения",
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="start_time",
            field=models.DateTimeField(
                help_text="ДД.ММ.ГГГГ 00:00", verbose_name="Время начала"
            ),
        ),
    ]
