# Generated by Django 4.2 on 2024-07-29 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_settings_end_time_alter_settings_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attempt",
            name="settings",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logs",
                to="main.settings",
                verbose_name="Настройки",
            ),
        ),
    ]
